"""scoring, surveys and sales

Revision ID: a91ed86ed698
Revises: d5b13c0d67e6
Create Date: 2026-09-09 14:13:16.566512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

SERVICE_TYPE_VALUES = (
    'RESIDENTIAL_SOLAR', 'PM_SURYA_GHAR', 'COMMERCIAL_SOLAR', 'INDUSTRIAL_SOLAR',
    'AGRICULTURE_SOLAR', 'GROUND_MOUNTED_SOLAR', 'EXISTING_SOLAR_UPGRADE',
    'SOLAR_MAINTENANCE', 'PANEL_CLEANING', 'GENERAL_ENQUIRY',
)

NEW_ENUM_TYPES = ('survey_status', 'opportunity_stage')


def _service_type():
    """Reuse the existing service_type enum rather than re-creating it.

    On PostgreSQL an enum is a database-wide object; a second CREATE TYPE
    fails. The initial migration owns this type.
    """
    if op.get_bind().dialect.name == 'postgresql':
        return postgresql.ENUM(*SERVICE_TYPE_VALUES, name='service_type', create_type=False)
    return sa.Enum(*SERVICE_TYPE_VALUES, name='service_type')


revision: str = 'a91ed86ed698'
down_revision: Union[str, None] = 'd5b13c0d67e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', _service_type(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('bands', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_configs_service'), 'scoring_configs', ['service'], unique=True)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service', _service_type(), nullable=True),
    sa.Column('stage', sa.Enum('NEW', 'CONTACTED', 'SURVEY', 'QUOTATION', 'WON', 'LOST', name='opportunity_stage'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quotation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_assigned_to_id'), 'opportunities', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_opportunities_classification'), 'opportunities', ['classification'], unique=False)
    op.create_index(op.f('ix_opportunities_customer_id'), 'opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=True)
    op.create_index(op.f('ix_opportunities_next_follow_up_at'), 'opportunities', ['next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_opportunities_score'), 'opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_opportunities_stage'), 'opportunities', ['stage'], unique=False)
    op.create_table('site_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service', _service_type(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'SCHEDULED', 'ASSIGNED', 'VISITED', 'COMPLETED', 'QUOTATION_REQUIRED', 'CANCELLED', name='survey_status'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('preferred_time', sa.String(length=30), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_surveys_assigned_to_id'), 'site_surveys', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_site_surveys_customer_id'), 'site_surveys', ['customer_id'], unique=False)
    op.create_index(op.f('ix_site_surveys_lead_id'), 'site_surveys', ['lead_id'], unique=False)
    op.create_index(op.f('ix_site_surveys_status'), 'site_surveys', ['status'], unique=False)
    op.create_table('opportunity_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_notes_opportunity_id'), 'opportunity_notes', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_notes_opportunity_id'), table_name='opportunity_notes')
    op.drop_table('opportunity_notes')
    op.drop_index(op.f('ix_site_surveys_status'), table_name='site_surveys')
    op.drop_index(op.f('ix_site_surveys_lead_id'), table_name='site_surveys')
    op.drop_index(op.f('ix_site_surveys_customer_id'), table_name='site_surveys')
    op.drop_index(op.f('ix_site_surveys_assigned_to_id'), table_name='site_surveys')
    op.drop_table('site_surveys')
    op.drop_index(op.f('ix_opportunities_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_next_follow_up_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_customer_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_classification'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_assigned_to_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_scoring_configs_service'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for type_name in NEW_ENUM_TYPES:
            postgresql.ENUM(name=type_name).drop(bind, checkfirst=True)
