"""ai conversations

Revision ID: d5b13c0d67e6
Revises: d7136b958406
Create Date: 2026-09-09 13:00:33.276617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

SERVICE_TYPE_VALUES = (
    'RESIDENTIAL_SOLAR', 'PM_SURYA_GHAR', 'COMMERCIAL_SOLAR', 'INDUSTRIAL_SOLAR',
    'AGRICULTURE_SOLAR', 'GROUND_MOUNTED_SOLAR', 'EXISTING_SOLAR_UPGRADE',
    'SOLAR_MAINTENANCE', 'PANEL_CLEANING', 'GENERAL_ENQUIRY',
)

NEW_ENUM_TYPES = ('conversation_state', 'turn_speaker')


def _service_type():
    """Reuse the existing service_type enum rather than re-creating it.

    On PostgreSQL an enum is a database-wide object; a second CREATE TYPE
    fails. See the initial migration, which owns this type.
    """
    if op.get_bind().dialect.name == 'postgresql':
        return postgresql.ENUM(*SERVICE_TYPE_VALUES, name='service_type', create_type=False)
    return sa.Enum(*SERVICE_TYPE_VALUES, name='service_type')


revision: str = 'd5b13c0d67e6'
down_revision: Union[str, None] = 'd7136b958406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_attempt_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('GREETING', 'QUALIFYING', 'ENDED', name='conversation_state'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('service', _service_type(), nullable=True),
    sa.Column('collected', sa.JSON(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('final_intent', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_call_attempt_id'), 'conversations', ['call_attempt_id'], unique=True)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('AI', 'CUSTOMER', name='turn_speaker'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_call_attempt_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for type_name in NEW_ENUM_TYPES:
            postgresql.ENUM(name=type_name).drop(bind, checkfirst=True)
