"""campaigns, call queue and telephony

Revision ID: d7136b958406
Revises: 37b12c214dbd
Create Date: 2026-09-09 12:23:37.713349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7136b958406'
down_revision: Union[str, None] = '37b12c214dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'STOPPED', 'COMPLETED', name='campaign_status'), nullable=False),
    sa.Column('service', sa.Enum('RESIDENTIAL_SOLAR', 'PM_SURYA_GHAR', 'COMMERCIAL_SOLAR', 'INDUSTRIAL_SOLAR', 'AGRICULTURE_SOLAR', 'GROUND_MOUNTED_SOLAR', 'EXISTING_SOLAR_UPGRADE', 'SOLAR_MAINTENANCE', 'PANEL_CLEANING', 'GENERAL_ENQUIRY', name='service_type'), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_rules', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DIALING', 'COMPLETED', 'EXHAUSTED', 'SUPPRESSED', 'CANCELLED', name='campaign_lead_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_disposition', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'lead_id', name='uq_campaign_lead')
    )
    op.create_index(op.f('ix_campaign_leads_campaign_id'), 'campaign_leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_lead_id'), 'campaign_leads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_next_attempt_at'), 'campaign_leads', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_campaign_leads_status'), 'campaign_leads', ['status'], unique=False)
    op.create_table('call_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('campaign_lead_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_call_id', sa.String(length=120), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'RINGING', 'IN_PROGRESS', 'COMPLETED', 'NO_ANSWER', 'BUSY', 'FAILED', name='call_state'), nullable=False),
    sa.Column('disposition', sa.Enum('QUALIFIED_HOT', 'QUALIFIED_WARM', 'QUALIFIED_COLD', 'SITE_SURVEY_REQUESTED', 'CALLBACK_REQUESTED', 'HUMAN_TRANSFER', 'NO_ANSWER', 'BUSY', 'SWITCHED_OFF', 'NOT_INTERESTED', 'WRONG_NUMBER', 'EXISTING_CUSTOMER', 'SERVICE_REQUEST', 'DO_NOT_CALL', 'AI_ERROR', 'TELEPHONY_ERROR', name='call_disposition'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_payload', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['campaign_lead_id'], ['campaign_leads.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_attempts_campaign_id'), 'call_attempts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_campaign_lead_id'), 'call_attempts', ['campaign_lead_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_customer_id'), 'call_attempts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_disposition'), 'call_attempts', ['disposition'], unique=False)
    op.create_index(op.f('ix_call_attempts_lead_id'), 'call_attempts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_call_attempts_provider_call_id'), 'call_attempts', ['provider_call_id'], unique=True)
    op.create_index(op.f('ix_call_attempts_state'), 'call_attempts', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_attempts_state'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_provider_call_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_lead_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_disposition'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_customer_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_campaign_lead_id'), table_name='call_attempts')
    op.drop_index(op.f('ix_call_attempts_campaign_id'), table_name='call_attempts')
    op.drop_table('call_attempts')
    op.drop_index(op.f('ix_campaign_leads_status'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_next_attempt_at'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_lead_id'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_campaign_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
